#import <Foundation/Foundation.h>

typedef NSString SpectacleWindowAction;

extern SpectacleWindowAction *const kSpectacleWindowActionUndo;
extern SpectacleWindowAction *const kSpectacleWindowActionRedo;
extern SpectacleWindowAction *const kSpectacleWindowActionLarger;
extern SpectacleWindowAction *const kSpectacleWindowActionSmaller;
extern SpectacleWindowAction *const kSpectacleWindowActionNone;
extern SpectacleWindowAction *const kSpectacleWindowActionCenter;
extern SpectacleWindowAction *const kSpectacleWindowActionFullscreen;
extern SpectacleWindowAction *const kSpectacleWindowActionLeftHalf;
extern SpectacleWindowAction *const kSpectacleWindowActionUpperLeft;
extern SpectacleWindowAction *const kSpectacleWindowActionLowerLeft;
extern SpectacleWindowAction *const kSpectacleWindowActionRightHalf;
extern SpectacleWindowAction *const kSpectacleWindowActionUpperRight;
extern SpectacleWindowAction *const kSpectacleWindowActionLowerRight;
extern SpectacleWindowAction *const kSpectacleWindowActionTopHalf;
extern SpectacleWindowAction *const kSpectacleWindowActionBottomHalf;
extern SpectacleWindowAction *const kSpectacleWindowActionNextDisplay;
extern SpectacleWindowAction *const kSpectacleWindowActionPreviousDisplay;
extern SpectacleWindowAction *const kSpectacleWindowActionNextThird;
extern SpectacleWindowAction *const kSpectacleWindowActionPreviousThird;

extern BOOL SpectacleIsUndoWindowAction(SpectacleWindowAction *action);
extern BOOL SpectacleIsRedoWindowAction(SpectacleWindowAction *action);

extern BOOL SpectacleIsNextDisplayWindowAction(SpectacleWindowAction *action);
extern BOOL SpectacleIsPreviousDisplayWindowAction(SpectacleWindowAction *action);

extern BOOL SpectacleIsMovingToDisplayWindowAction(SpectacleWindowAction *action);
