#import <Foundation/Foundation.h>

typedef NSString SpectacleWindowAction;

extern SpectacleWindowAction *const kSpectacleWindowActionUndo;
extern SpectacleWindowAction *const kSpectacleWindowActionRedo;
extern SpectacleWindowAction *const kSpectacleWindowActionLarger;
extern SpectacleWindowAction *const kSpectacleWindowActionSmaller;
extern SpectacleWindowAction *const kSpectacleWindowActionNone;
extern SpectacleWindowAction *const kSpectacleWindowActionCenter;
extern SpectacleWindowAction *const kSpectacleWindowActionFullscreen;
extern SpectacleWindowAction *const kSpectacleWindowActionLeftHalf;
extern SpectacleWindowAction *const kSpectacleWindowActionUpperLeft;
extern SpectacleWindowAction *const kSpectacleWindowActionLowerLeft;
extern SpectacleWindowAction *const kSpectacleWindowActionRightHalf;
extern SpectacleWindowAction *const kSpectacleWindowActionUpperRight;
extern SpectacleWindowAction *const kSpectacleWindowActionLowerRight;
extern SpectacleWindowAction *const kSpectacleWindowActionTopHalf;
extern SpectacleWindowAction *const kSpectacleWindowActionBottomHalf;
extern SpectacleWindowAction *const kSpectacleWindowActionNextDisplay;
extern SpectacleWindowAction *const kSpectacleWindowActionPreviousDisplay;
extern SpectacleWindowAction *const kSpectacleWindowActionNextThird;
extern SpectacleWindowAction *const kSpectacleWindowActionPreviousThird;

BOOL SpectacleIsUndoWindowAction(SpectacleWindowAction *action);
BOOL SpectacleIsRedoWindowAction(SpectacleWindowAction *action);

BOOL SpectacleIsNextDisplayWindowAction(SpectacleWindowAction *action);
BOOL SpectacleIsPreviousDisplayWindowAction(SpectacleWindowAction *action);
BOOL SpectacleIsMovingToDisplayWindowAction(SpectacleWindowAction *action);
